### PR TITLE
Sass compiler swap and styles fix

### PR DESCRIPTION
**Pull request by mciastek**

### CODE REVIEW

**Comment by sedouard** [comment]
hey @mciastek thanks for making the fix!

When I try picking up your fix (`ember install https://github.com/mciastek/ember-calendar.git#a170bfd7fb67183da94a98d5e04dd21cbeaa6bba`) I seem to get the same error. Confirmed your version is sitting in my `node_modules` too...

**Comment by mciastek** [comment]
@sedouard In my project I use `2.5.0` version of ember-cli.

**Comment by Arkham** [comment]
Unfortunately we are using broccoli-sass in our project and therefore I can't merge this PR as is. I think the best option would be to leave the choice of the sass compiler to the user.

**Comment by Arkham** [comment]
Scratch that, I've release `0.3.9` which ships this change. Thanks for your help!

**Pull request closed without merging**
